test:
  workers:
    number: 2
  rounds:
    - label: Register Voter
      txNumber: 100
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 20
      workload:
        module: benchmarks/evoting/workload/registerVoter.js
    - label: Cast Vote
      txNumber: 50  # each of 2 workers will send 50 = 100 total votes
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 10
      workload:
        module: benchmarks/evoting/workload/castVote.js       
    - label: Get Results
      txDuration: 30
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: benchmarks/evoting/workload/getResults.js

# As of know no arguments
# refer to caliper-benchmarks/benchmarks/samples/fabric/fabcar/config.yaml
